{{- if .Values.jupyter.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    {{- include "featurologists.labels" . | nindent 4 }}
    app: jupyter
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "featurologists.selectorLabels" . | nindent 6 }}
      app: jupyter
  template:
    metadata:
      labels:
        {{- include "featurologists.selectorLabels" . | nindent 8 }}
        app: jupyter
    spec:
      volumes:
      {{- include "gitClone.volumes" . | nindent 6 }}

      initContainers:
      {{- include "gitClone.initContainer" . | nindent 6 }}

      containers:
      - name: main
        image: {{ required ".Values.jupyter.image.repo is required!" .Values.jupyter.image.repo }}:
               {{- required ".Values.jupyter.image.tag is required!" .Values.jupyter.image.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: {{ include "gitClone.volumeName" . }}
          mountPath: /project
        workingDir: /project
        ports:
        - name: http
          containerPort: 8888
        resources:
          {{- toYaml .Values.jupyter.resources | nindent 12 }}
        command:
        - bash
        - -c
        - >-
          cd /project
          && make setup
          && jupyter {{ .Values.jupyter.mode }} \
              --no-browser \
              --ip=0.0.0.0 \
              --port=8888 \
              --allow-root \
              --NotebookApp.token= \
              --notebook-dir=/project \
              --NotebookApp.shutdown_no_activity_timeout=7200 \
              --MappingKernelManager.cull_idle_timeout=7200
{{- end }}
