apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "featurologists.fullname" . }}-jupyter
  labels:
    {{- include "featurologists.labels" . | nindent 4 }}
    app: jupyter
spec:
  selector:
    matchLabels:
      {{- include "featurologists.selectorLabels" . | nindent 6 }}
      app: jupyter
  template:
    metadata:
      labels:
        {{- include "featurologists.selectorLabels" . | nindent 8 }}
        app: jupyter
    spec:
      initContainers:
      {{- define "gitClone.initContainer" -}}
      containers:
      - name: main
        image: "{{ .Values.jupyter.image.repository | required }}:{{ .Values.jupyter.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8888
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.jupyter.resources | nindent 12 }}
        command:
        - bash
        - -c
        - >-
          jupyter {{ .Values.jupyter.mode | required }} \
              --no-browser \
              --ip=0.0.0.0 \
              --port=8888 \
              --allow-root \
              --NotebookApp.token= \
              --notebook-dir=/workdir \
              --NotebookApp.shutdown_no_activity_timeout=7200 \
              --MappingKernelManager.cull_idle_timeout=7200
