{{- if .Values.jupyter.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    {{- include "featurologists.labels" . | nindent 4 }}
    app: jupyter
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
  selector:
    {{- include "featurologists.selectorLabels" . | nindent 4 }}
    app: jupyter
{{- end }}
