apiVersion: v1
kind: Service
metadata:
  name: {{ include "featurologists.fullname" . }}-jupyter
  labels:
    {{- include "featurologists.selectorLabels" . | nindent 8 }}
    app: jupyter
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
  selector:
    {{- include "featurologists.selectorLabels" . | nindent 8 }}
    app: jupyter
