{{- if .Values.kafkaclient.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkaclient
  labels:
    {{- include "featurologists.labels" . | nindent 4 }}
    app: kafkaclient
spec:
  selector:
    matchLabels:
      {{- include "featurologists.selectorLabels" . | nindent 6 }}
      app: kafkaclient
  template:
    metadata:
      labels:
        {{- include "featurologists.selectorLabels" . | nindent 8 }}
        app: kafkaclient
    spec:
      volumes:
      {{- include "gitClone.volumes" . | nindent 6 }}

      initContainers:
      {{- include "gitClone.initContainer" . | nindent 6 }}

      containers:
      - name: main
        image: {{ required ".Values.common.image.repo is required!" .Values.common.image.repo }}:
               {{- required ".Values.common.image.tag is required!" .Values.common.image.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: {{ include "gitClone.volumeName" . }}
          mountPath: /project
        workingDir: /project
        ports:
        - name: http
          containerPort: 8888
        resources:
          {{- toYaml .Values.kafkaclient.resources | nindent 12 }}
        command:
        - bash
        - -c
        - >-
          make setup
          && featurologists client run-kafka \
               --endpoint {{ required ".Values.kafkaclient.app.endpoint is requried!" .Values.kafkaclient.app.endpoint }} \
               --delay {{ required ".Values.kafkaclient.app.delay is requried!" .Values.kafkaclient.app.delay }} \
               --num-total {{ .Values.kafkaclient.app.numTotal | quote }}
{{- end }}
