name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout commit
      uses: actions/checkout@v2

    - name: Setup Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Cache pip
      uses: actions/cache@v2.1.5
      with:
        key: pip-lint-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements*.txt') }}
        path: ~/.cache/pip
        restore-keys: |
          pip-lint-

    - name: Cache pre-commit
      uses: actions/cache@v2.1.5
      with:
        key: pre-commit-
        path: ~/.cache/pre-commit
        restore-keys: |
          pre-commit-

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        make setup

    - name: Run linters
      run: |
        make lint
      env:
        CI_LINT_RUN: 1

    - name: Run tests
      run: |
        make test
